#!/usr/bin/env bash
# Shared Claude Code provider metadata for setup and the Bubblewrap launcher.
#
# Mirror of codex-providers.sh for the Claude Code backend (tools/claude-articulated,
# tools/claude-supervisor). The Codex registry is untouched; the two coexist so a
# host can run either agent against the same harness.
#
# One provider: the Anthropic API, keyed by $claude_home/anthropic_api_key (written
# once by tools/install_claude_bwrap.sh from $ANTHROPIC_API_KEY, mode 0600).

CLAUDE_PROVIDER_DEFAULT="anthropic"
# The default Claude Code model. The [1m] suffix selects the 1M-token context
# window, matching the ~1M window the Codex config runs with. Overridable at setup
# time (--model / ARTSCRIPT_CLAUDE_MODEL).
CLAUDE_ANTHROPIC_MODEL_DEFAULT="claude-fable-5[1m]"
CLAUDE_API_KEY_FILE="anthropic_api_key"

claude_provider_validate() {
  case "${1:-}" in
    anthropic)
      printf '%s\n' "$1"
      ;;
    *)
      return 2
      ;;
  esac
}

# The host:port pairs the egress namespace relays for a provider: only the
# inference endpoint. SANDBOX_EGRESS_HOSTS overrides the list.
claude_provider_egress_hosts() {
  local provider="$1"
  case "$provider" in
    anthropic)
      printf '%s\n' "api.anthropic.com:443"
      ;;
    *)
      return 2
      ;;
  esac
}

# Read one string out of $claude_home/settings.json: `claude_settings_get FILE
# env.ANTHROPIC_MODEL`. Empty when the file or key is missing. Claude Code's config
# is JSON, so python3 (already required for the egress relay) does the parsing.
claude_settings_get() {
  local file="$1"
  local dotted="$2"
  [[ -r "$file" ]] || return 0
  python3 - "$file" "$dotted" <<'PY' 2>/dev/null || true
import json, sys
value = json.load(open(sys.argv[1]))
for key in sys.argv[2].split("."):
    if not isinstance(value, dict):
        sys.exit(0)
    value = value.get(key)
if isinstance(value, (str, int, float)):
    print(value)
PY
}

# True when settings.json denies both web tools. WebSearch is executed on the
# provider's side and so bypasses the egress namespace, exactly like Codex's
# web_search; WebFetch is client-side but denied too so the sinkhole log stays
# about the model's traffic, not attempted fetches.
claude_settings_denies_web() {
  local file="$1"
  [[ -r "$file" ]] || return 1
  python3 - "$file" <<'PY' 2>/dev/null
import json, sys
deny = set(json.load(open(sys.argv[1])).get("permissions", {}).get("deny", []))
sys.exit(0 if {"WebSearch", "WebFetch"} <= deny else 1)
PY
}

# Write the dedicated Claude Code state directory's settings.json. Everything
# unattended runs need lives here so that the launcher only has to pin the
# environment and bind the directory:
#   model                  mirrored into the sandbox environment (ANTHROPIC_MODEL)
#   permissions.deny       both web tools (see claude_settings_denies_web)
#   skipDangerousModePermissionPrompt
#                          the bypass-permissions consent, pre-accepted
#   telemetry off          nothing but inference traffic leaves the namespace
claude_provider_write_settings() {
  local claude_home="$1"
  local provider="$2"
  local model="$3"
  mkdir -p "$claude_home"
  chmod 0700 "$claude_home"
  python3 - "$claude_home/settings.json" "$provider" "$model" <<'PY'
import json, sys
path, provider, model = sys.argv[1:4]
env = {
    "ANTHROPIC_MODEL": model,
    "DISABLE_AUTOUPDATER": "1",
    "DISABLE_TELEMETRY": "1",
    "DISABLE_ERROR_REPORTING": "1",
    "DISABLE_BUG_COMMAND": "1",
    "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC": "1",
}
settings = {
    "_comment": "Generated by tools/install_claude_bwrap.sh -- unattended worker.",
    "provider": provider,
    "model": model,
    "env": env,
    "permissions": {"deny": ["WebSearch", "WebFetch"]},
    # The unattended --dangerously-skip-permissions launch must not stop at the
    # Bypass Permissions consent dialog. Since Claude Code 2.1.259 the consent
    # lives here (older builds read bypassPermissionsModeAccepted from
    # .claude.json and migrate it into this key on first start; the global
    # config seed below is kept for them). Without it every sandboxed session
    # hangs on the dialog and the supervisor reports discovery_failed.
    "skipDangerousModePermissionPrompt": True,
    "includeCoAuthoredBy": False,
}
with open(path, "w") as handle:
    json.dump(settings, handle, indent=2)
    handle.write("\n")
PY
  chmod 0600 "$claude_home/settings.json"
}

# Seed the global Claude Code config so the first launch inside the sandbox asks
# nothing: onboarding done, bypass-permissions accepted, and the sandbox project
# paths trusted. Claude Code keeps this file inside CLAUDE_CONFIG_DIR, which the
# launcher points at the bound state directory.
claude_provider_write_global_config() {
  local claude_home="$1"
  shift
  mkdir -p "$claude_home"
  python3 - "$claude_home/.claude.json" "$@" <<'PY'
import json, os, sys
path = sys.argv[1]
projects = sys.argv[2:]
config = {}
if os.path.exists(path):
    try:
        config = json.load(open(path))
    except (OSError, json.JSONDecodeError):
        config = {}
config["hasCompletedOnboarding"] = True
config["bypassPermissionsModeAccepted"] = True
# Otherwise the first launch tries to fetch the official plugin marketplace from
# github.com -- refused by the egress namespace, but six DNS-REFUSED lines in
# every run's audit log that are not the agent's doing.
config["officialMarketplaceAutoInstallAttempted"] = True
config["officialMarketplaceAutoInstalled"] = True
config.setdefault("theme", "dark")
trusted = config.setdefault("projects", {})
for project in projects:
    entry = trusted.setdefault(project, {})
    entry["hasTrustDialogAccepted"] = True
    entry.setdefault("allowedTools", [])
with open(path, "w") as handle:
    json.dump(config, handle, indent=2)
    handle.write("\n")
PY
  chmod 0600 "$claude_home/.claude.json"
}
