#!/usr/bin/env bash
# Shared Codex provider metadata for setup and the Bubblewrap launcher.
#
# One provider: the OpenAI API, authenticated by the API-key login Codex itself
# writes into the dedicated state's auth.json (tools/install_codex_bwrap.sh runs
# `codex login --with-api-key` from $OPENAI_API_KEY once; the key is never written
# into TOML or passed into the bwrap environment).

CODEX_PROVIDER_DEFAULT="openai"
CODEX_OPENAI_MODEL_DEFAULT="gpt-5.6-sol"

codex_provider_validate() {
  case "${1:-}" in
    openai)
      printf '%s\n' "$1"
      ;;
    *)
      return 2
      ;;
  esac
}

# The host:port pairs the egress namespace relays for a provider: only the
# inference endpoint. SANDBOX_EGRESS_HOSTS overrides the list.
codex_provider_egress_hosts() {
  local provider="$1"
  case "$provider" in
    openai)
      printf '%s\n' "api.openai.com:443"
      ;;
    *)
      return 2
      ;;
  esac
}

# The dedicated Codex state's config.toml: provider, model, the trusted sandbox
# project paths (an untrusted project makes an unattended run prompt), and the
# subagent cap. web_search stays "disabled" -- the launcher refuses to start
# otherwise, since a model-side search bypasses the egress namespace.
codex_provider_write_config() {
  local codex_home="$1"
  local model="$2"
  local project_dir="$3"
  mkdir -p "$codex_home"
  chmod 0700 "$codex_home"
  cat > "$codex_home/config.toml" <<EOF
# Generated by tools/install_codex_bwrap.sh — unattended worker.
model_provider = "openai"
model = "$model"
model_reasoning_effort = "medium"
model_reasoning_summary = "detailed"
hide_agent_reasoning = false
show_raw_agent_reasoning = true
approvals_reviewer = "auto_review"
forced_login_method = "api"
cli_auth_credentials_store = "file"
web_search = "disabled"

# The sandbox mounts the checkout at this fixed path (tools/codex-articulated
# owns the mount); an untrusted project would make an unattended run prompt.
[projects."/home/ubuntu"]
trust_level = "trusted"

[projects."/home/ubuntu/articulated_script"]
trust_level = "trusted"

[projects."$project_dir"]
trust_level = "trusted"

[notice]
hide_full_access_warning = true

[agents]
# pose_windows rounds spawn one subagent per window (7+ observed); the
# default cap of 6 made batch spawns fail ("agent thread limit reached")
# and drove the orchestrator into serial spawn->wait->close rounds.
max_threads = 6
EOF
}
